[project]
name = "validarsenhas"
version = "0.1.0"
description = "Simple password validation API"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.121.1",
    "pydantic>=2.12.4",
    "uvicorn>=0.38.0",
]
